### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by Srilakshman213** [Srilakshman213/upload#4]
https://www.codejava.net/frameworks/spring-boot/file-download-upload-rest-api-examples

**Comment by Srilakshman213** [comment]
https://medium.com/analytics-vidhya/strive-to-upload-or-download-files-using-spring-boot-964336b3ddc7

**Comment by Srilakshman213** [comment]
https://www.javaguides.net/2020/04/spring-boot-file-upload-download-rest-api-example.html

**Comment by Srilakshman213** [comment]
[PDF Compression White Paper.pdf](https://github.com/Srilakshman213/upload/files/11414821/PDF.Compression.White.Paper.pdf)

**Comment by Srilakshman213** [comment]
[java.zip](https://github.com/Srilakshman213/upload/files/11415060/java.zip)

**Comment by Srilakshman213** [comment]
{"accountData":{"accountNumber":"033000005","firstName":"SAMUEL","lastName":"SMITH","shortName":"CONVERT$","displayName":"SAMUEL SMITH","accountClassification":"36","lineOfBusiness":"NF","lineOfBusinessDescription":"National Financial","mailAddressLine1":"31 SUNSET STREET","mailAddressLine2":"PALM BEACH GARDENS","regType":"SIRA","regTypeDescription":"Subcustodial IRA","regCode":"SIRA","citizenshipStatusCode":"2","citizenshipCountryCode":"048","state":"FL","city":"FLORIDA","zip":"33410","countryName":"UNITED STATES OF AMERICA","ssn":"829338999","ssnCode":"S","superOffice":"033","superBranch":"033","currentShareQ":"0.0","addendumOnFile":"Y","houseHoldNetWorth":"1","customerID":"B82624760","regRep1Code":"130","phoneNumber":"9879879766","eMail":"RENWICK.ALICE@MAILHOST.UK.Z","customerMailingAddressLine1":"31 SUNSET STREET","customerMailingAddressLine2":"PALM BEACH GARDENS","customerMailingState":"FL","customerMailingCity":"FLORIDA","customerMailingZip":"33410","customerMailingCountryName":"UNITED STATES OF AMERICA","customerLegalAddressLine1":"31 SUNSET STREET","customerLegalAddressLine2":"PALM BEACH GARDENS","customerLegalState":"FL","customerLegalCity":"FLORIDA","customerLegalZip":"33410","customerLegalCountryName":"UNITED STATES OF AMERICA","accountOwnersModelList":[{"accountNumber":"033000005","customerID":"B82624760","firstName":"SAMUEL","lastName":"SMITH","relTypeCode":"BENE","taxReportingType":"S","taxReportingNumber":"829338999","dateOfBirth":"1986-10-06","orderID":"1","dateOfDeath":"2017-01-05"}]},"productData":{"productDetails":{"cusipNumber":"124997289","nsccId":"0000347014308006","productName":"CAIS MILLENNIUM INTL LTD CLASS I","dtcEligibleInd":true,"aipEligibleInd":true,"assetStatus":"APPROVED","productStatus":"ACTIVE","frozenReasons":"OOS","customerQty":1,"price":"33","assetClass":"OTHER","eligibleAcctType":"RETIRE_AND_NON_RETIRE","unitizedInd":false,"productId":"SUL","capitalCallInd":true,"altInvstNetworkInd":false,"offshoreInd":true,"stateOfIncorporation":"DE","ffosExclProdInd":false,"independentValuationInd":false,"proprietaryProductInd":false,"registeredAct1933Ind":false,"registeredAct1940Ind":false,"placementFeeScheduleInd":false,"placementFeeSchedule":[],"registrationStatusInd":false,"settleViaDTCCInd":false,"accreditedInvestorsInd":true,"qualifiedInstitutionalInvestorsInd":true,"qualifiedEligiblePersonInd":true,"percentage25BenefitPlanInd":true,"inKindContributionsOrDistInd":true,"cftcInd":false,"fiscalYearEnd":"12/31","maximumInvestment":"0","escrowAccount":null,"fundTaxStructure":null,"fidelityAiFundInd":true,"ffosLobAllowedInd":true,"iwsLobAllowedInd":true,"nfLobAllowedInd":true,"piLobAllowedInd":true,"fcmLobAllowedInd":true,"pairedFundInd":false},"dividendDetails":{"payoutType":"CASH","divDataSource":null,"taxReporting":"FORM_K_1","distFrequency":"NO_DISTRIBUTION","ubtiInd":true,"debtFinancedInd":false},"reconciliationDetails":{"custReportSource":null,"custReportFrequency":"MONTHLY","tolerance":"0","reconFtp":"NFSCAISRECON.CSV.PGP","oosReconStatus":"REMEDIATED"},"investmentDetails":{"purchaseDetails":{"subscriptionFormInd":false,"additionalSubscriptionFormInd":false,"commisionBasedPop":"0","feeBasedPop":"0","minInitialInvst":"100000","minSubsequentInvst":"0","waivePlacementFeeInd":false,"orderFullfill":"NON_AIP","paymentMethod":"WIRE","repetitiveCode":"033000045"},"redemptionDetails":{"redemptionsOrWithdrawalsInd":true,"redemptionFormInd":false,"redemptionFrequency":null,"holdBackInd":false,"holdBackPercentage":"10","holdBackCusip":"124997313","orderFullfill":"NON_AIP"}},"transferDetails":{"qualifiedAccountSponsorFormsReqInd":false,"nonQualifiedAccountSponsorFormsReqInd":false,"qualifiedAccountOriginalFormsReqInd":false,"nonQualifiedAccountOriginalFormsReqInd":false},"calendarScheduleDetails":{"investmentScheduleDetails":{}},"riskDetails":{"certificationStatus":"IGO","periodOfAudit":"2013-12-31"}},"assetReviewData":{"assetReviewId":"11811","assetName":"CAIS MILLENNIUM INTL LTD CLASS I","requestorName":"AI","assetClass":"OTHER","assetReviewStatus":null,"startDate":"2011-08-02","endDate":"2011-08-02"},"sponsorData":{"sponsorId":"8005","sponsorName":"CAPITAL INTEGRATION SYSTEMS LLC"},"tradeData":{"tradeId":1606626,"action":"BUY","navReason":null,"dividendOption":"NONE","pricePerShare":"50.41","tradeStatus":"NIGO","isOverride":false,"settleDate":"2023-05-03","approvalStatus":"NA","isDTCCTrade":false,"isManagerApproval":false,"shareQty":"240.23804","statusDate":"2023-05-04T10:57:53.471877-04:00","grossAmount":"12110.40","netAmount":"12110.40","isSendToCactus":false,"tradeDate":"2023-05-03","orderCondition":"SOLICITED","pairedFundTradeInd":false,"tradeSource":{"sourceCode":"I"},"tradeFeeData":{"cdscFee":"0.00","redemptionFee":"0.00","concession":"0.00","loadAmount":"0.00","loadPercent":"0","commissionCode":null,"transactionFee":"0.000000","miscFee":"0.00"},"commitmentCallData":{"isCapitalCommitment":false,"commitmentAmount":"0.000000","isCapitalCall":true,"commitmentTradeId":1601645,"capitalCommitmentTradeStatus":"COMPLETE","isInitialDrawdown":false,"initialDrawdownAmount":"0.000000"},"initiatedTradeData":{"tradeId":0,"offsetAccount":"980300033","runningCollectiveBalance":"0.0000","disbursementNumber":"0"},"userData":{"userId":"AITST01","firstName":"Chandrashekhar","lastName":"Yadav"}},"messages":{"status":"SUCCESSFUL","messageList":[{"code":"W300017","title":null,"detail":null,"status":null,"severity":"WARNING","source":null,"links":null,"parameters":null,"messageContent":"Unable to process Mainframe Initiation"}]}}

**Comment by Srilakshman213** [comment]
{
    "accountData": {
        "accountNumber": "033000005"
    },
    "productData": {
        "productDetails": {
            "cusipNumber": "124997289"
        }
    },
    "tradeData": {
        "action": "BUY",
        "tradeStatus": "PENDING",
        "settleDate": "2023-05-03",
        "pricePerShare": "50.41",
        "isDTCCTrade": false,
        "grossAmount": "12110.40",
        "isSendToCactus": false,
        "tradeDate": "2023-05-03",
        "orderCondition": "SOLICITED",
        "notes": null,
        "tradeSource": {
            "sourceCode": "I",
            "sourceCodeDesc": null,
            "transactionID": null
        },
        "tradeFeeData": null,
        "conditionalTradeData": null,
        "commitmentCallData": {
            "isCapitalCall": true,
            "isCapitalCommitment": false,
            "commitmentTradeId": 1601645
        },
        "mainframeData": null,
        "tradeOverrideData": null,
        "userData": {
            "userId": "AITST01",
            "firstName": "Chandrashekhar",
            "lastName": "Yadav",
            "userEmailID": null
        },
        "contactData": null,
        "initiatedTradeData": {
            "tradeId": 0
        }
    }
}

**Comment by Srilakshman213** [comment]
Content-Type:application/json
FID-LOG-TRACKING-ID:{"logTrackingId": "SKS-TEST-RETISSUE0007"}
FID-FBT-PRODUCT-IDENTITY:{"appId":"AP125214","productId":"9BF"}
FID-FBT-PRINCIPAL-IDENTITY:{"requestorId":"AITST01","principalDomain":"Representative","principalRole":"Representative"}
FID-FBT-SECURITY-EXTENSION:{"version": "3","securityExtensionItems": [{"key":"TERMID","value":"00B0478"}]}
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE2ODM2MTEyOTAsInN1YiI6IkFJVFNUMDEiLCJjbGllbnRfaWQiOiJCNnMxMEN5TlA0QmFweVR5Y295VEYzREo0aXZGaHBzRyIsImlhdCI6MTY4MzYxMDk5MCwiaXNzIjoiZmJ0IiwiYXVkIjoiZmJ0X25nX2FsdGludl90cmFkZV9tYW5hZ2VtZW50X2FwMTUxMDEwLGZidF9uZ19hbHRpbnZfdHJhZGVfZWRpdF9ydWxlc19hcDE1MTAxNSxmYnRfYWx0ZXJuYXRpdmVpbnZlc3RtZW50c3Byb2R1Y3RzZWFyY2hhcGlfYXAxNDQyMzEiLCJ2ZXJzaW9uIjoiMS4wLjAiLCJuYmYiOjE2ODM2MTA5OTAsImprdSI6Imh0dHBzOi8va21hYXNwdWItcWEuZm1yLmNvbTo4NDQzL3NlY3VyaXR5LWtleWFkbWluL2p3a3M_a2lkPVFBX0FTWU1NRVRSSUNfS0VZX0ZJX0FQMTM2NTA4X0ZKV1QlNUUzOTQiLCJhcHBpZCI6IkFQMTQ2MDY5IiwiY29uc3VtZXJfY2FsbF90eXBlIjoiSU5URVJOQUwiLCJqdGkiOiI1OWU2MDhmNS02MWYwLTQxZTctOTYwNy0zNWVjOGFjOGJiMTgifQ.oieF8iculUSbfNALJqlwkTYZZAM3ZtJSF2vWc8T3l0aUVwCk7_QJSMP9AoW7IsPy6UrT98UFR8XVCemS92fBQ28ZfZcHGAeH9oVJknHTCDJrvIc8V0G1AyXkbnlLyz7YBKmFzNQQRo_SF3kfNw6ASdQiup0muDdlF6ipo1hd2lo8s_VlYmVfKoHFWAFYrvDBnPY1v71w4Ca0atxrgGWTyzmCOt9Z2glaL3Uqe8B3KO2u3AV9kBw6r72GDyV75V8Y1m9yos9ozFW2QTLc6-5Eoht474C3HY-MshoOhIv_T4H7qk_hA3b9HLh72r668nd1KNTto7lvdkSxKoUDJ02dvw

**Comment by Srilakshman213** [comment]
[src.zip](https://github.com/Srilakshman213/upload/files/11501992/src.zip)

**Comment by Srilakshman213** [comment]
RROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[LoginAPIService -> HttpClient -> HttpClient -> HttpClient]: 
  NullInjectorError: No provider for HttpClient!
NullInjectorError: R3InjectorError(AppModule)[LoginAPIService -> HttpClient -> HttpClient -> HttpClient]: 
  NullInjectorError: No provider for HttpClient!
    at NullInjector.get (core.mjs:7493:27)
    at R3Injector.get (core.mjs:7914:33)
    at R3Injector.get (core.mjs:7914:33)
    at R3Injector.get (core.mjs:7914:33)
    at injectInjectorOnly (core.mjs:618:33)
    at Module.ɵɵinject (core.mjs:622:60)
    at Object.LoginAPIService_Factory [as factory] (login-api.service.ts:7:29)
    at R3Injector.hydrate (core.mjs:8015:35)
    at R3Injector.get (core.mjs:7903:33)
    at ChainedInjector.get (core.mjs:12084:36)
    at resolvePromise (zone.js:1214:31)
    at resolvePromise (zone.js:1168:17)
    at zone.js:1281:17
    at _ZoneDelegate.invokeTask (zone.js:409:31)
    at core.mjs:23896:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23896:36)
    at _ZoneDelegate.invokeTask (zone.js:408:60)
    at Object.onInvokeTask (core.mjs:24197:33)
    at _ZoneDelegate.invokeTask (zone.js:408:60)
    at Zone.runTask (zone.js:178:47)

**Comment by Srilakshman213** [comment]
Signon Exception:  - Object reference not set to an instance of an object

**Comment by Srilakshman213** [comment]
import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class LoginAPIService {
  constructor( private http: HttpClient) {}
  login(username:string, password: string) {
    const url='https://wsosgsit.fmr.com/FBSIsignonAPI/api/FBSISignOn';
    const requestBody = {
      AppID: "9BF",
      RunMode: "SIT",
      resourceField: [
        { resource: 'PVTOFFR'},
        { resource: 'BR-RES10'}
      ]
    };
    const headers=new HttpHeaders().set('Authorization','Basic'+btoa(username + ':' + password));
    return this.http.post(url,requestBody, { headers });
  }
}

**Comment by Srilakshman213** [comment]
Display API Error Modal


User
I have a api which returns a certain value, if the value is not returned I want to display anngx bootstrap modal saying "incorrect details" in its body

ChatGPT
To achieve this functionality, you can use Angular's HttpClient to make the API request and check the response. If the expected value is not returned, you can display an Angular Bootstrap modal with the "incorrect details" message in its body. Here's an example of how you can accomplish this:

First, make sure you have Angular Bootstrap installed. You can install it using npm:
css
Copy code
npm install ngx-bootstrap --save
Import the necessary modules in your Angular component. Here's an example of how it can be done:
typescript
Copy code
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { BsModalService, BsModalRef } from 'ngx-bootstrap/modal';

@Component({
  selector: 'app-your-component',
  template: `
    
  `
})
export class YourComponent {
  modalRef: BsModalRef;

  constructor(private http: HttpClient, private modalService: BsModalService) { }

  makeApiRequest() {
    this.http.get('your-api-url').subscribe(
      (response: any) => {
        // Check the response here
        if (response.value !== expectedValue) {
          this.openModal();
        }
      },
      (error) => {
        console.error('API request error:', error);
      }
    );
  }

  openModal() {
    this.modalRef = this.modalService.show(ModalContentComponent);
    this.modalRef.content.message = 'Incorrect details';
  }
}
Create a separate component for your modal content. In this example, we'll name it ModalContentComponent. Here's an example implementation:
typescript
Copy code
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-modal-content',
  template: `
    <div class="modal-header">
      <h4 class="modal-title">Modal Title</h4>
      <button type="button" class="close" aria-label="Close" (click)="closeModal()">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      {{ message }}
    </div>
  `
})
export class ModalContentComponent {
  @Input() message: string;

  constructor(private modalRef: BsModalRef) { }

  closeModal() {
    this.modalRef.hide();
  }
}
